Add controllers and jpa
ulanzetz/javka pull request #8
Opened 2019-11-03 18:00 UTC by GSKryachko

2019-11-03 18:26 UTC, ulanzetz requested changes

2019-11-03 18:26 UTC, ulanzetz commented on src/main/java/ru/naumen/javka/domain/Group.java
> +    public long getCreator() { return creator;}
форматирование нужно

2019-11-03 18:26 UTC, ulanzetz commented on src/main/java/ru/naumen/javka/services/FileServiceImpl.java
> +        String query = String.format("SELECT * FROM files WHERE \"parentId\"=%d;", directoryId);
injection? там должны быть prepared statements где-то

2019-11-03 18:26 UTC, ulanzetz commented on src/main/java/ru/naumen/javka/services/FileServiceImpl.java
> +        fileRepository.getEntityManager().createNativeQuery(query).executeUpdate();
это логика должна быть на уровне реп, сервис например должен принимать несколько репозиториев и проверять например права

2019-11-03 18:26 UTC, ulanzetz commented on src/main/java/ru/naumen/javka/services/FileServiceImpl.java
> +        fileRepository.save(file);
зачем писать файл в БД, если мы не сохранили его в сторадж

2019-11-03 18:26 UTC, ulanzetz commented on src/main/java/ru/naumen/javka/services/FileServiceImpl.java
> +        String ownFilesQuery = String.format("SELECT * FROM files WHERE creator=%d;", userId);
можно за 1 запрос с union

2019-11-03 18:26 UTC, ulanzetz commented on src/main/java/ru/naumen/javka/services/GroupServiceImpl.java
> +            String query = String.format("INSERT INTO user_groups VALUES (%d, %d)", userId, group.getId());
можно за 1 запрос

2019-11-04 06:33 UTC, GSKryachko commented on src/main/java/ru/naumen/javka/services/FileServiceImpl.java
> +        String query = String.format("SELECT * FROM files WHERE \"parentId\"=%d;", directoryId);
Я сделаю через prepared statements, но тут же число подставляется, а не строка. Не получится заинджектить.

2019-11-11 16:46 UTC, merged